name: upload-thesis
on:
    schedule:
        # the job runs twice per day
        - cron:  '*/30 12,23 * 1-7 *'
jobs:
    compile-thesis:
        name: Compile thesis
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository 
              uses: actions/checkout@v2

            - name: Compile pdf
              uses: xu-cheng/latex-action@v2
              with:
                  root_file: thesis.tex
                  latexmk_shell_escape: true

            - name: Upload Artifact
              uses: actions/upload-artifact@v2
              with:
                  name: thesis
                  path: thesis.pdf
                  retention-days: 1

    upload-thesis:
        name: Upload thesis
        runs-on: ubuntu-latest
        needs: compile-thesis

        steps:
            - name: Download Artifact
              uses: actions/download-artifact@v2
              with:
                  name: thesis

            - name: Upload to Google Drive
              uses: satackey/action-google-drive@v1
              with:
                  skicka-tokencache-json: ${{ secrets.SKICKA_TOKENCACHE_JSON }}
                  upload-from: ./thesis.pdf
                  upload-to: /GitHub/master-thesis

                  google-client-id: ${{ secrets.GOOGLE_CLIENT_ID }}
                  google-client-secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
